Repository Pan-Canadian-Genome-Library/daco, pull requests merged in 2024-12, with the labels that each got.

#93 🧹 Chore / Rename Applications Edit route
  apps/api/src/resources/swagger.yaml
  apps/api/src/routes/application-router.ts
Labels: daco-api

#95 Chore: Add Jenkinsfile
  Jenkinsfile
Labels: DevOps, chore

#92 #82: Add device warning banner
  apps/ui/src/components/layouts/StatusBarWrapper.tsx
  apps/ui/src/components/pages/dashboard/ApplicationStatusBar.tsx
  apps/ui/src/components/pages/dashboard/cards/ApplicationCard.tsx
  apps/ui/src/pages/dashboard.tsx
Labels: daco-ui

#96 📝 Chore: Migration before API startup
  README.md
  apps/api/docker-compose.yml
  apps/api/package.json
Labels: documentation

#97 #85: My Applications API - Add get application by ID
  apps/api/src/api/application-api.ts
  apps/api/src/resources/swagger.yaml
  apps/api/src/routes/application-router.ts
  apps/api/tests/api/application-api.test.ts
  apps/api/tests/testUtils.ts
Labels: daco-api

#98 #84: Add the Create New Application endpoint
  apps/api/src/api/application-api.ts
  apps/api/src/resources/swagger.yaml
  apps/api/src/routes/application-router.ts
  apps/api/src/service/application-service.ts
  apps/api/tests/api/application-api.test.ts
  apps/api/tests/services/application-service.test.ts
Labels: daco-api

#111 #94: i18n integrations
  apps/ui/package.json
  apps/ui/src/components/Footer.tsx
  apps/ui/src/components/Header.tsx
  apps/ui/src/components/layouts/PageLayout.tsx
  apps/ui/src/components/pages/dashboard/ApplicationStatusBar.tsx
  apps/ui/src/components/pages/dashboard/cards/ApplicationCard.tsx
  apps/ui/src/components/pages/dashboard/cards/NewApplicationCard.tsx
  apps/ui/src/i18n/locale/en/enTranslations.json
  apps/ui/src/i18n/locale/fr/frTranslations.json
  apps/ui/src/i18n/translations.ts
  apps/ui/src/main.tsx
  apps/ui/src/pages/App.tsx
  apps/ui/src/pages/dashboard.tsx
  apps/ui/src/pages/index.tsx
  apps/ui/tsconfig.json
  apps/ui/vite.config.ts
  pnpm-lock.yaml
Labels: UI

#125 🕸️ Bug: Resolve build errors
  apps/api/src/api/states.ts
  apps/api/src/routes/types.ts
Labels: bug
